version: "3.8"
services:
  kong:
    image: kong:3.4
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml:ro
    depends_on:
      - orchestrator

  orchestrator:
    build: ./orchestrator
    image: orchestrator:latest
    environment:
      RETRIEVER_URL: "http://retriever:5001/retrieve"
      PROCESSOR_URL: "http://processor:5003/process"
      POLICY_URL: "http://policy:5004/policy"
    ports:
      - "5002:5002"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - retriever
      - processor
      - policy

  retriever:
    build: ./retriever
    image: retriever:latest
    ports:
      - "5001:5001"

  processor:
    build: ./processor
    image: processor:latest
    ports:
      - "5003:5003"

  policy:
    build: ./policy
    image: policy:latest
    ports:
      - "5004:5004"
